sources:
    - name: raw
      schema: parcel_raw_data
      tables:
        - name: parcel
          identifier: raw_cc_parcel
        - name: parcel_product
          identifier: raw_cc_parcel_product